---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy Nginx site config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/myapp
  notify: reload nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/myapp
    dest: /etc/nginx/sites-enabled/myapp
    state: link
  notify: reload nginx

- name: Remove default nginx site if exists
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Ensure nginx running and enabled
  service:
    name: nginx
    state: started
    enabled: yes

